### ISSUE TITLE
RuntimeError when finetuning GPT-2 on M1 with CPU

### ISSUE THREAD

**Issue by Belluxx** [stochasticai/xturing#144]
I am using this code:
```python
from xturing.datasets.instruction_dataset import InstructionDataset
from xturing.models import BaseModel

# Load the dataset
instruction_dataset = InstructionDataset('./dataset')

# Initializes the model
model = BaseModel.create('gpt2')

# Finetuned the model
model.finetune(dataset=instruction_dataset)

# Save the model
model.save('./gpt2_finetuned')
```

And i am getting this error when `model.finetune(dataset=instruction_dataset)` gets executed:
```
File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Here you can check the whole traceback if interested
<details>
  <summary>Full traceback</summary>

```
File "/Users/user/project/gpt2.py", line 8, in <module>
    model.finetune(dataset=instruction_dataset)
  File "/Users/user/project/venv/lib/python3.10/site-packages/xturing/models/causal.py", line 84, in finetune
    trainer.fit()
  File "/Users/user/project/venv/lib/python3.10/site-packages/xturing/trainers/lightning_trainer.py", line 178, in fit
    self.trainer.fit(self.lightning_model)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in _run
    call._call_callback_hooks(self, "on_fit_start")
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/lr_finder.py", line 125, in on_fit_start
    self.lr_find(trainer, pl_module)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/lr_finder.py", line 109, in lr_find
    self.optimal_lr = _lr_find(
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/tuner/lr_finder.py", line 269, in _lr_find
    _try_loop_run(trainer, params)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/tuner/lr_finder.py", line 495, in _try_loop_run
    loop.run()
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 193, in run
    self.setup_data()
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 235, in setup_data
    _check_dataloader_iterable(dl, source, trainer_fn)
  File "/Users/user/project/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
    iter(dataloader)  # type: ignore[call-overload]
  File "/Users/user/project/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/Users/user/project/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/user/project/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1043, in __init__
    w.start()
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/user/.pyenv/versions/3.10.10/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
</details>

**Comment by Surf-N-Code** [comment]
I am running into the exact same error

I am running the docker container like this: `docker run -p 5001:5000 --platform linux/amd64 -e WANDB_MODE=dryrun -e MICRO_BATCH_SIZE=1 -v ./data public.ecr.aws/t8g5g2q5/xturing:int4_finetuning`

**Comment by StochasticRomanAgeev** [comment]
Hi @Surf-N-Code @Belluxx,
Can you please send version of os and pip freeze result?

**Comment by Belluxx** [comment]
@StochasticRomanAgeev Sure

MacOS Ventura 13.2.1

Pip Freeze
```
absl-py==1.4.0
ai21==1.0.4
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
anyio==3.6.2
appnope==0.1.3
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
backcall==0.2.0
backoff==2.2.1
bitsandbytes==0.38.1
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
cohere==4.1.4
comm==0.1.3
contourpy==1.0.7
cycler==0.11.0
datasets==2.11.0
debugpy==1.6.7
decorator==5.1.1
deepspeed==0.9.0
dill==0.3.6
entrypoints==0.4
evaluate==0.4.0
executing==1.2.0
fastapi==0.95.1
ffmpy==0.3.0
filelock==3.11.0
fonttools==4.39.3
frozenlist==1.3.3
fsspec==2023.4.0
gradio==3.26.0
gradio_client==0.1.2
h11==0.14.0
hjson==3.1.0
httpcore==0.17.0
httpx==0.24.0
huggingface-hub==0.13.4
idna==3.4
ipykernel==6.22.0
ipython==8.12.0
ipywidgets==8.0.6
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.17.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
lightning-utilities==0.8.0
linkify-it-py==2.0.0
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdit-py-plugins==0.3.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
nest-asyncio==1.5.6
networkx==3.1
ninja==1.11.1
nltk==3.8.1
numpy==1.24.2
openai==0.27.4
orjson==3.8.10
packaging==23.1
pandas==2.0.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.2.0
prompt-toolkit==3.0.38
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==11.0.0
pydantic==1.10.7
pydub==0.25.1
Pygments==2.15.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==2.0.1.post0
pytz==2023.3
PyYAML==6.0
pyzmq==25.0.2
regex==2023.3.23
requests==2.28.2
responses==0.18.0
rouge-score==0.1.2
semantic-version==2.10.0
sentencepiece==0.1.98
six==1.16.0
sniffio==1.3.0
stack-data==0.6.2
starlette==0.26.1
sympy==1.11.1
tokenizers==0.13.3
toolz==0.12.0
torch==2.0.0
torchmetrics==0.11.4
tornado==6.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.27.3
typing_extensions==4.5.0
tzdata==2023.3
uc-micro-py==1.0.1
urllib3==1.26.15
uvicorn==0.21.1
wcwidth==0.2.6
websockets==11.0.1
wget==3.2
widgetsnbextension==4.0.7
xturing==0.0.9
xxhash==3.2.0
yarl==1.8.2
```

**Comment by Belluxx** [comment]
Update, i upgraded to Ventura 13.3.1 and it still gives the same error

**Comment by Surf-N-Code** [comment]
@StochasticRomanAgeev sure :) 

I am on mac os 12.6

absl-py==1.4.0
ai21==1.0.4
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
anyio==3.6.2
appnope==0.1.3
appscript==1.2.2
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
backcall==0.2.0
backoff==2.2.1
bitsandbytes==0.38.1
certifi==2022.12.7
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.1.3
cohere==4.1.4
comm==0.1.3
contourpy==1.0.7
cx-Freeze==6.14.7
cycler==0.11.0
datasets==2.11.0
debugpy==1.6.7
decorator==5.1.1
deepspeed==0.9.0
dill==0.3.6
distlib==0.3.6
docx2pdf==0.1.8
entrypoints==0.4
evaluate==0.4.0
executing==1.2.0
fastapi==0.95.1
ffmpeg-python==0.2.0
ffmpy==0.3.0
filelock==3.11.0
Flask==2.2.3
fonttools==4.39.3
frozenlist==1.3.3
fsspec==2023.4.0
future==0.18.3
git-filter-repo==2.38.0
gradio==3.26.0
gradio_client==0.1.2
h11==0.14.0
hjson==3.1.0
httpcore==0.17.0
httpx==0.24.0
huggingface-hub==0.13.4
identify==2.5.22
idna==3.4
iniconfig==2.0.0
ipykernel==6.22.0
ipython==8.12.0
ipywidgets==8.0.6
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.17.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
lightning-utilities==0.8.0
linkify-it-py==2.0.0
lxml==4.9.2
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdit-py-plugins==0.3.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
nest-asyncio==1.5.6
networkx==3.1
ninja==1.11.1
nltk==3.8.1
nodeenv==1.7.0
numpy==1.24.2
openai==0.27.4
orjson==3.8.10
packaging==23.1
pandas==2.0.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.2.0
pluggy==1.0.0
pre-commit==3.2.2
prompt-toolkit==3.0.38
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==11.0.0
pydantic==1.10.7
pydub==0.25.1
Pygments==2.15.0
PyOgg==0.6.14a1
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.3.0
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==2.0.1.post0
pytz==2023.3
PyYAML==6.0
pyzmq==25.0.2
regex==2023.3.23
requests==2.28.2
responses==0.18.0
rouge-score==0.1.2
semantic-version==2.10.0
sentencepiece==0.1.98
six==1.16.0
sniffio==1.3.0
stack-data==0.6.2
starlette==0.26.1
sympy==1.11.1
tokenizers==0.13.3
toolz==0.12.0
torch==2.0.0
torchmetrics==0.11.4
tornado==6.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.27.3
typing_extensions==4.5.0
tzdata==2023.3
uc-micro-py==1.0.1
urllib3==1.26.15
uvicorn==0.21.1
virtualenv==20.21.0
wcwidth==0.2.6
websockets==11.0.1
Werkzeug==2.2.3
wget==3.2
widgetsnbextension==4.0.7
xturing==0.0.9
xxhash==3.2.0
yarl==1.8.2

**Comment by StochasticRomanAgeev** [comment]
I tested with same lib versions and OS, but cannot find an issue
Are you sure dataset has correct format?

Can you try with text dataset?
```python
dataset = TextDataset( {
    "text": ["first text", "second text"],
    "target": ["first text", "second text"],
})
```

**Comment by Belluxx** [comment]
@StochasticRomanAgeev With the following code i get the same error:
```python
from xturing.datasets.text_dataset import TextDataset
from xturing.models import BaseModel

# Load the dataset
instruction_dataset = TextDataset( {
    "text": ["first text", "second text"],
    "target": ["first text", "second text"],
})

# Initializes the model
model = BaseModel.create('gpt2')

# Finetuned the model
model.finetune(dataset=instruction_dataset)

# Save the model
model.save('./gpt2_weights')
```

**Comment by StochasticRomanAgeev** [comment]
Can you try to use latest version of xturing?

```python
pip install xturing -U
```
We expect that it will work better
Because I have same setup with you and script is working for me

**Comment by Belluxx** [comment]
@StochasticRomanAgeev I am now getting this error:
```
WARNING: CUDA is not available, using CPU instead, can be very slow
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
dlopen(/Users/user/MyProject/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/user/MyProject/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/MyProject/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (no such file), '/Users/user/MyProject/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
trioton not installed.
Traceback (most recent call last):
  File "/Users/user/MyProject/gpt2.py", line 14, in <module>
    model.finetune(dataset=instruction_dataset)
  File "/Users/user/MyProject/venv/lib/python3.10/site-packages/xturing/models/causal.py", line 83, in finetune
    trainer = self._make_trainer(dataset)
  File "/Users/user/MyProject/venv/lib/python3.10/site-packages/xturing/models/causal.py", line 67, in _make_trainer
    return BaseTrainer.create(
  File "/Users/user/MyProject/venv/lib/python3.10/site-packages/xturing/registry.py", line 14, in create
    return cls.registry[class_key](*args, **kwargs)
  File "/Users/user/MyProject/venv/lib/python3.10/site-packages/xturing/trainers/lightning_trainer.py", line 134, in __init__
    model_engine.model.print_trainable_parameters()
  File "/Users/user/MyProject/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2LMHeadModel' object has no attribute 'print_trainable_parameters'
```

As you can see i am getting a `trioton not installed` warning, it's a typo right?

**Comment by StochasticRomanAgeev** [comment]
Hi again, @Belluxx 
Sorry for inconvenience, we will release patch asap to fix this problem
For now you can just comment that line or use `gpt2_lora`
