### ISSUE TITLE
Doesn't it work on Mac M1?

### ISSUE THREAD

**Issue by blackcon** [stochasticai/xturing#159]
Hello. Thank you for sharing this project :)

I try to run a `example/llama/llama_lora.py`  on my Mac book(M1),
but it doesn't work with below error message.

How can I run it on M1?

- Command & Error message
  ```bash
  (xturing) ➜  llama git:(main) python llama_lora.py
  WARNING: CUDA is not available, using CPU instead, can be very slow
  CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
  CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
  dlopen(/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (no such file), '/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
  trioton not installed.
  Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:09<00:00,  3.41it/s]
  trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
  trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
  GPU available: True (mps), used: False
  TPU available: False, using: 0 TPU cores
  IPU available: False, using: 0 IPUs
  HPU available: False, using: 0 HPUs
  WARNING: CUDA is not available, using CPU instead, can be very slow
  CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
  CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
  dlopen(/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (no such file), '/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
  trioton not installed.
  Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:10<00:00,  3.26it/s]
  trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
  trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
  GPU available: True (mps), used: False
  TPU available: False, using: 0 TPU cores
  IPU available: False, using: 0 IPUs
  HPU available: False, using: 0 HPUs
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
      exitcode = _main(fd, parent_sentinel)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
      prepare(preparation_data)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
      _fixup_main_from_path(data['init_main_from_path'])
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
      main_content = runpy.run_path(main_path,
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/runpy.py", line 289, in run_path
      return _run_module_code(code, init_globals, run_name,
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/runpy.py", line 96, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/Users/user/works/personal/xturing/examples/llama/llama_lora.py", line 8, in <module>
      model.finetune(dataset=instruction_dataset)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/xturing/models/causal.py", line 84, in finetune
      trainer.fit()
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/xturing/trainers/lightning_trainer.py", line 181, in fit
      self.trainer.fit(self.lightning_model)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
      call._call_and_handle_interrupt(
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
      return trainer_fn(*args, **kwargs)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
      self._run(model, ckpt_path=ckpt_path)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in _run
      call._call_callback_hooks(self, "on_fit_start")
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 190, in _call_callback_hooks
      fn(trainer, trainer.lightning_module, *args, **kwargs)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/callbacks/lr_finder.py", line 125, in on_fit_start
      self.lr_find(trainer, pl_module)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/callbacks/lr_finder.py", line 109, in lr_find
      self.optimal_lr = _lr_find(
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/tuner/lr_finder.py", line 269, in _lr_find
      _try_loop_run(trainer, params)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/tuner/lr_finder.py", line 495, in _try_loop_run
      loop.run()
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 193, in run
      self.setup_data()
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 235, in setup_data
      _check_dataloader_iterable(dl, source, trainer_fn)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 383, in _check_dataloader_iterable
      iter(dataloader)  # type: ignore[call-overload]
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
      return self._get_iterator()
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
      return _MultiProcessingDataLoaderIter(self)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1043, in __init__
      w.start()
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/process.py", line 121, in start
      self._popen = self._Popen(self)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
      return _default_context.get_context().Process._Popen(process_obj)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
      return Popen(process_obj)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
      super().__init__(process_obj)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
      self._launch(process_obj)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
      prep_data = spawn.get_preparation_data(process_obj._name)
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
      _check_not_importing_main()
    File "/Users/user/miniconda3/envs/xturing/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
      raise RuntimeError('''
  RuntimeError:
          An attempt has been made to start a new process before the
          current process has finished its bootstrapping phase.
  
          This probably means that you are not using fork to start your
          child processes and you have forgotten to use the proper idiom
          in the main module:
  
              if __name__ == '__main__':
                  freeze_support()
                  ...
  
          The "freeze_support()" line can be omitted if the program
          is not going to be frozen to produce an executable.
  ```

**Comment by StochasticRomanAgeev** [comment]
Hi, @blackcon 
Can you update our library version?

**Comment by blackcon** [comment]
@StochasticRomanAgeev 
Yes, I try to run after update a version. (0.1.0 -> 0.1.1)
nevertheless, occurred same error.

**Comment by StochasticRomanAgeev** [comment]
Hi @blackcon,
I was checking how it can happen and found that it can be because of RAM 
LLama on cpu will be loaded in fp32, so it will take huge amount of RAM, you should probably try different model

**Comment by blackcon** [comment]
> Hi @blackcon, I was checking how it can happen and found that it can be because of RAM LLama on cpu will be loaded in fp32, so it will take huge amount of RAM, you should probably try different model

okay. I try with different model
