### ISSUE TITLE
Can't install: assert len(weights) == expected_node_count

### ISSUE THREAD

**Issue by blueberry64** [stochasticai/xTuring#243]
`pip install xturing` 

produces this error:

`ERROR: Exception:
Traceback (most recent call last):
  File "/home/deanroland/summarization/.venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/deanroland/summarization/.venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/deanroland/summarization/.venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/deanroland/summarization/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/deanroland/summarization/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count`

It seems to install if I comment out the assert.  len(weights) == 154 and expected_node_count == 156.  I figure that's close enough lol.

**Comment by tushar2407** [comment]
Hi @blueberry64! Seems like the issue not with xTuring library. Please refer to [this](https://github.com/pypa/pip/issues/10851) issue. 
Hope this helps!
