### ISSUE TITLE
CUDA Not found?

### ISSUE THREAD

**Issue by basemaly** [stochasticai/xTuring#249]
Sorry again for the continued problems. After running pip install xturing, I get the following error. It seems there's a problem finding CUDA, but I've got it installed in the specified path: 

```
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2'
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\basem\Dev\DeepSpeed\setup.py", line 164, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\basem\Dev\DeepSpeed\setup.py", line 51, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tushar2407** [comment]
Hi @basemaly , 
Can you check what the deepspeed version being installed? Try downgrading it to 0.8.0 or 0.8.2. 
Got it from this [link](https://github.com/OptimalScale/LMFlow/issues/185).
If this does not work, try to locate the CUDA on your system and make sure the path set is right. If you need assistance I can help!
