### ISSUE TITLE
Whether I could set multiple GPU to train the model?

### ISSUE THREAD

**Issue by zhuang-li** [stochasticai/xturing#69]
Hi This is a very interesting work. I am curious whether I could set multi-GPUs to train the model as the original Alpaca did?

**Comment by StochasticRomanAgeev** [comment]
Hi @zhuang-li, 
Yes, our library natively support multi-gpu training.
All you need is to run same code on a multi-gpu machine.

Please let us know if you need any further information. Thank you.

**Comment by zhuang-li** [comment]
Thank you! I met some problems when ```pip install xturing```.  May you take a look?

```
Collecting tensorboardX==1.8
  Using cached tensorboardX-1.8-py2.py3-none-any.whl (216 kB)
Requirement already satisfied: protobuf>=3.2.0 in /home/ubuntu/anaconda3/envs/py3.8/lib/python3.8/site-packages (from tensorboardX==1.8->deepspeed->xturing) (3.15.8)
INFO: pip is looking at multiple versions of tensorboardx to determine which version is compatible with other requirements. This could take a while.
Collecting deepspeed
  Using cached deepspeed-0.5.5.tar.gz (488 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.5.4.tar.gz (483 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.5.3.tar.gz (477 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.5.2.tar.gz (477 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.5.1.tar.gz (476 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.5.0.tar.gz (475 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.4.5.tar.gz (457 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of tensorboardx to determine which version is compatible with other requirements. This could take a while.
  Using cached deepspeed-0.4.4.tar.gz (457 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.4.3.tar.gz (451 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.4.2.tar.gz (448 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.4.1.tar.gz (445 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.4.0.tar.gz (444 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torchvision>=0.4.0 in /home/ubuntu/anaconda3/envs/py3.8/lib/python3.8/site-packages (from deepspeed->xturing) (0.10.1)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached deepspeed-0.3.16.tar.gz (385 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.15.tar.gz (382 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.14.tar.gz (341 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.13.tar.gz (334 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.12.tar.gz (333 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.10.tar.gz (281 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.9.tar.gz (268 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.8.tar.gz (259 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.7.tar.gz (258 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.6.tar.gz (212 kB)
  Preparing metadata (setup.py) ... done
  Using cached deepspeed-0.3.5.tar.gz (207 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lmdhze4_/deepspeed_d715df98fdbd4870958fb1f6c65c2831/setup.py", line 32, in <module>
          install_requires = fetch_requirements('requirements/requirements.txt')
        File "/tmp/pip-install-lmdhze4_/deepspeed_d715df98fdbd4870958fb1f6c65c2831/setup.py", line 28, in fetch_requirements
          with open(path, 'r') as fd:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by zhuang-li** [comment]
I solved this problem already by re-installing deepspeed.

**Comment by zhuang-li** [comment]
Another question is that do you have some pre-defined parameters for training different model? I tried to trained the GPT2. It seems the default setting does not produce a good model at all.

**Comment by Toan-Do** [comment]
Hi @zhuang-li 

This is our generated text after fine-tuning GPT-2 after 3 epochs: 
`Generated output by the model: ['Why LLM models are becoming so important?Because a better model is more important than alternatives like wind turbines, modern energy sources, natural gas, and renewable energy']`

Lets check our documentation to see how to change the pre-defined parameters for fine-tuning: https://xturing.stochastic.ai/finetune/configure

Also GPT-2 model is quite small then it perform not too good. You should try LLaMA, Cerebras-GPT, GPT-J, OPT,  Galactica or Bloom. We have supported these models and provided examples in our README.

**Comment by zhuang-li** [comment]
Thank you... And sorry for my more questions.

When I use two A100s to train GPTj. Here is my code.

```
from xturing.datasets.instruction_dataset import InstructionDataset
from xturing.models import BaseModel

instruction_dataset = InstructionDataset("./alpaca_data")
# Initializes the model
model = BaseModel.create("gptj")
# Finetuned the model
model.finetune(dataset=instruction_dataset)
# Once the model has been finetuned, you can start doing inferences
output = model.generate(texts=["I am happy now. Write a tweet for me to express my feeling. "])
print("Generated output by the model: {}".format(output))
# Save the model
model.save("./gptj_weights")
```

It reports the error. 

```
Downloading (…)lve/main/config.json: 100%|██████████| 977/977 [00:00<00:00, 1.88MB/s]
Downloading (…)model.bin.index.json: 100%|██████████| 25.8k/25.8k [00:00<00:00, 119kB/s]
Downloading (…)l-00001-of-00013.bin: 100%|██████████| 967M/967M [01:05<00:00, 14.8MB/s]
Downloading (…)l-00002-of-00013.bin: 100%|██████████| 956M/956M [01:05<00:00, 14.6MB/s] 
Downloading (…)l-00003-of-00013.bin: 100%|██████████| 998M/998M [01:14<00:00, 13.3MB/s] 
Downloading (…)l-00004-of-00013.bin: 100%|██████████| 923M/923M [04:30<00:00, 3.41MB/s] 
Downloading (…)l-00005-of-00013.bin: 100%|██████████| 956M/956M [01:03<00:00, 15.0MB/s] 
Downloading (…)l-00006-of-00013.bin: 100%|██████████| 998M/998M [02:30<00:00, 6.62MB/s] 
Downloading (…)l-00007-of-00013.bin: 100%|██████████| 923M/923M [00:53<00:00, 17.3MB/s] 
Downloading (…)l-00008-of-00013.bin: 100%|██████████| 956M/956M [00:56<00:00, 16.9MB/s] 
Downloading (…)l-00009-of-00013.bin: 100%|██████████| 998M/998M [01:34<00:00, 10.6MB/s] 
Downloading (…)l-00010-of-00013.bin: 100%|██████████| 923M/923M [02:06<00:00, 7.32MB/s] 
Downloading (…)l-00011-of-00013.bin: 100%|██████████| 956M/956M [01:57<00:00, 8.14MB/s] 
Downloading (…)l-00012-of-00013.bin: 100%|██████████| 998M/998M [00:59<00:00, 16.8MB/s] 
Downloading (…)l-00013-of-00013.bin: 100%|██████████| 782M/782M [00:43<00:00, 17.8MB/s] 
Downloading shards: 100%|██████████| 13/13 [21:20<00:00, 98.54s/it]:43<00:00, 19.0MB/s] 
Loading checkpoint shards: 100%|██████████| 13/13 [00:48<00:00,  3.76s/it]
Downloading (…)okenizer_config.json: 100%|██████████| 763/763 [00:00<00:00, 1.07MB/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 798k/798k [00:01<00:00, 738kB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 526kB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 2.14M/2.14M [00:01<00:00, 1.65MB/s]
Downloading (…)in/added_tokens.json: 100%|██████████| 4.33k/4.33k [00:00<00:00, 6.65MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 438/438 [00:00<00:00, 852kB/s]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA A100 80GB PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Traceback (most recent call last):
  File "/home/zli/xturing_app/gpt2_alpaca.py", line 8, in <module>
    model.finetune(dataset=instruction_dataset)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/xturing/models/causal.py", line 84, in finetune
    trainer.fit()
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/xturing/trainers/lightning_trainer.py", line 181, in fit
    self.trainer.fit(self.lightning_model)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 896, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 82, in _call_setup_hook
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 132, in setup
    raise MisconfigurationException("The Batch size finder is not supported with distributed strategies.")
lightning_fabric.utilities.exceptions.MisconfigurationException: The Batch size finder is not supported with distributed strategies.
```

It seems to due to using two GPUs. So I reduce the GPU to one. And I get the out of memory error.

```
Loading checkpoint shards: 100%|██████████| 13/13 [01:03<00:00,  4.87s/it]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA A100 80GB PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Missing logger folder: /home/zli/xturing_app/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Finding best initial lr: 100%|██████████| 100/100 [00:32<00:00,  3.35it/s]`Trainer.fit` stopped: `max_steps=100` reached.
Finding best initial lr: 100%|██████████| 100/100 [00:32<00:00,  3.05it/s]
Failed to compute suggestion for learning rate because there are not enough points. Increase the loop iteration limits or the size of your dataset/dataloader.
Restoring states from the checkpoint path at /home/zli/xturing_app/.lr_find_cecba623-70f3-4fe6-88d2-6035b3b3378f.ckpt
Restored all states from the checkpoint at /home/zli/xturing_app/.lr_find_cecba623-70f3-4fe6-88d2-6035b3b3378f.ckpt
Batch size 2 failed, trying batch size 1
Batch size 1 failed, trying batch size 0
Traceback (most recent call last):
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/tuner/batch_size_scaling.py", line 184, in _run_power_scaling
    _try_loop_run(trainer, params)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/tuner/batch_size_scaling.py", line 331, in _try_loop_run
    loop.run()
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 218, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 185, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 261, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 142, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1266, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 158, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 224, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 114, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/adamw.py", line 171, in step
    adamw(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/adamw.py", line 321, in adamw
    func(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/adamw.py", line 564, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 79.35 GiB total capacity; 78.01 GiB already allocated; 85.12 MiB free; 78.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zli/xturing_app/gpt2_alpaca.py", line 8, in <module>
    model.finetune(dataset=instruction_dataset)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/xturing/models/causal.py", line 84, in finetune
    trainer.fit()
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/xturing/trainers/lightning_trainer.py", line 181, in fit
    self.trainer.fit(self.lightning_model)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in _run
    call._call_callback_hooks(self, "on_fit_start")
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 185, in on_fit_start
    self.scale_batch_size(trainer, pl_module)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 171, in scale_batch_size
    new_size = _scale_batch_size(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/tuner/batch_size_scaling.py", line 81, in _scale_batch_size
    new_size = _run_power_scaling(trainer, new_size, batch_arg_name, max_trials, params)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/tuner/batch_size_scaling.py", line 199, in _run_power_scaling
    _reset_dataloaders(trainer)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/tuner/batch_size_scaling.py", line 323, in _reset_dataloaders
    loop.setup_data()
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 221, in setup_data
    train_dataloader = _request_dataloader(source)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 328, in _request_dataloader
    return data_source.dataloader()
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 295, in dataloader
    return call._call_lightning_module_hook(self.instance.trainer, self.name, pl_module=self.instance)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 142, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/xturing/trainers/lightning_trainer.py", line 61, in train_dataloader
    self.train_dl = torch.utils.data.DataLoader(
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/lightning_fabric/utilities/data.py", line 330, in wrapper
    init(obj, *args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 357, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/lightning_fabric/utilities/data.py", line 330, in wrapper
    init(obj, *args, **kwargs)
  File "/home/zli/.conda/envs/py310/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 232, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0
```
Even the batch size is 1. The model can not fit into an A100 with 80 GB memory. 

I really appreciate if you could help me solve this problem.

**Comment by Toan-Do** [comment]
Hi @zhuang-li , 

Thank you for rasing it. Could you please try with GPT-J LoRA instead, there are problems with GPT-J fine-tuning and we will fix it soon.
